<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\TesteParaEmpresaInfinity.Domain\TesteParaEmpresaInfinity.Domain.csproj" />
    <ProjectReference Include="..\TesteParaEmpresaInfinity.Repositorio\TesteParaEmpresaInfinity.Infra.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="MensagensErros\CodigoErro.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>CodigoErro.resx</DependentUpon>
    </Compile>
    <Compile Update="MensagensErros\MensagemErro.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>MensagemErro.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="MensagensErros\CodigoErro.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>CodigoErro.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="MensagensErros\MensagemErro.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>MensagemErro.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

</Project>
